"""Property definitions for Zendure devices."""

from typing import TypedDict, Literal


class PropertyDefinition(TypedDict):
    """Definition for a device property."""
    name: str
    type: Literal["int", "float", "string", "bool"]
    unit: str | None
    writable: bool
    ha_entity: Literal["sensor", "binary_sensor", "switch", "number"]
    device_class: str | None
    state_class: str | None
    conversion: str | None
    min_value: float | None
    max_value: float | None
    step: float | None


# Device properties (67 total)
DEVICE_PROPERTIES: dict[str, PropertyDefinition] = {
    # Category 1: Power Management (17 properties)
    "solarInputPower": {
        "name": "Solar Input Power",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "solarPower1": {
        "name": "Solar Power 1",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "solarPower2": {
        "name": "Solar Power 2",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "outputPackPower": {
        "name": "Output Pack Power",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "packInputPower": {
        "name": "Pack Input Power",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "gridInputPower": {
        "name": "Grid Input Power",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "outputHomePower": {
        "name": "Output Home Power",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "invOutputPower": {
        "name": "Inverter Output Power",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "energyPower": {
        "name": "Energy Power",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "outputLimit": {
        "name": "Output Limit",
        "type": "int",
        "unit": "W",
        "writable": True,
        "ha_entity": "number",
        "device_class": "power",
        "state_class": None,
        "conversion": None,
        "min_value": 0,
        "max_value": 10000,
        "step": 1,
    },
    "inputLimit": {
        "name": "Input Limit",
        "type": "int",
        "unit": "W",
        "writable": True,
        "ha_entity": "number",
        "device_class": "power",
        "state_class": None,
        "conversion": None,
        "min_value": 0,
        "max_value": 10000,
        "step": 1,
    },
    "solarPower1Cycle": {
        "name": "Solar Power 1 Cycle",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "solarPower2Cycle": {
        "name": "Solar Power 2 Cycle",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "outputPackPowerCycle": {
        "name": "Output Pack Power Cycle",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "gridInputPowerCycle": {
        "name": "Grid Input Power Cycle",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "packInputPowerCycle": {
        "name": "Pack Input Power Cycle",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "outputHomePowerCycle": {
        "name": "Output Home Power Cycle",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    
    # Category 2: Battery Management (8 properties)
    "electricLevel": {
        "name": "Battery Level",
        "type": "int",
        "unit": "%",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "battery",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "packState": {
        "name": "Pack State",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "remainOutTime": {
        "name": "Remain Out Time",
        "type": "int",
        "unit": "min",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "duration",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "remainInputTime": {
        "name": "Remain Input Time",
        "type": "int",
        "unit": "min",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "duration",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "packNum": {
        "name": "Pack Number",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "socSet": {
        "name": "SOC Set",
        "type": "int",
        "unit": "%",
        "writable": True,
        "ha_entity": "number",
        "device_class": "battery",
        "state_class": None,
        "conversion": "value/10",
        "min_value": 80,
        "max_value": 100,
        "step": 1,
    },
    "minSoc": {
        "name": "Minimum SOC",
        "type": "int",
        "unit": "%",
        "writable": True,
        "ha_entity": "number",
        "device_class": "battery",
        "state_class": None,
        "conversion": "value/10",
        "min_value": 5,
        "max_value": 100,
        "step": 1,
    },
    "socStatus": {
        "name": "SOC Status",
        "type": "int",
        "unit": "%",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "battery",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    
    # Category 3: AC Mode & Grid Control (9 properties)
    "acMode": {
        "name": "AC Mode",
        "type": "int",
        "unit": None,
        "writable": True,
        "ha_entity": "number",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": 1,
        "max_value": 2,
        "step": 1,
    },
    "chargingMode": {
        "name": "Charging Mode",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "gridReverse": {
        "name": "Grid Reverse",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "gridStandard": {
        "name": "Grid Standard",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "inverseMaxPower": {
        "name": "Inverse Max Power",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "gridOffMode": {
        "name": "Grid Off Mode",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "phaseCheck": {
        "name": "Phase Check",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "phaseSwitch": {
        "name": "Phase Switch",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "reverseState": {
        "name": "Reverse State",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    
    # Category 4: System & Device Info (9 properties)
    "masterSwitch": {
        "name": "Master Switch",
        "type": "int",
        "unit": None,
        "writable": True,
        "ha_entity": "switch",
        "device_class": "switch",
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "masterSoftVersion": {
        "name": "Master Software Version",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "masterhaerVersion": {
        "name": "Master Hardware Version",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "dspversion": {
        "name": "DSP Version",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "wifiState": {
        "name": "WiFi State",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "binary_sensor",
        "device_class": "connectivity",
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "strength": {
        "name": "WiFi Strength",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "signal_strength",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "hubState": {
        "name": "Hub State",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "buzzerSwitch": {
        "name": "Buzzer",
        "type": "int",
        "unit": None,
        "writable": True,
        "ha_entity": "switch",
        "device_class": "switch",
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "lampSwitch": {
        "name": "Lamp",
        "type": "int",
        "unit": None,
        "writable": True,
        "ha_entity": "switch",
        "device_class": "switch",
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    
    # Category 5: Temperature & Environmental (4 properties)
    "hyperTmp": {
        "name": "Hub Temperature",
        "type": "int",
        "unit": "°C",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "temperature",
        "state_class": "measurement",
        "conversion": "(value/10) - 273.15",
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "lowTemperature": {
        "name": "Low Temperature",
        "type": "int",
        "unit": "°C",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "temperature",
        "state_class": "measurement",
        "conversion": "(value/10) - 273.15",
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "heatState": {
        "name": "Heat State",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "binary_sensor",
        "device_class": "heat",
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "autoHeat": {
        "name": "Auto Heat",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    
    # Category 6: Ambient Light Control (4 properties)
    "ambientSwitch": {
        "name": "Ambient Light",
        "type": "int",
        "unit": None,
        "writable": True,
        "ha_entity": "switch",
        "device_class": "switch",
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "ambientLightNess": {
        "name": "Ambient Light Brightness",
        "type": "int",
        "unit": "%",
        "writable": True,
        "ha_entity": "number",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": 0,
        "max_value": 100,
        "step": 1,
    },
    "ambientLightColor": {
        "name": "Ambient Light Color",
        "type": "int",
        "unit": None,
        "writable": True,
        "ha_entity": "number",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": 0,
        "max_value": 16777215,
        "step": 1,
    },
    "ambientLightMode": {
        "name": "Ambient Light Mode",
        "type": "int",
        "unit": None,
        "writable": True,
        "ha_entity": "number",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": 0,
        "max_value": 10,
        "step": 1,
    },
    
    # Category 7: Advanced Settings (16 properties)
    "pvBrand": {
        "name": "PV Brand",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "VoltWakeup": {
        "name": "Voltage Wakeup",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "plugState": {
        "name": "Plug State",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "circuitCheckMode": {
        "name": "Circuit Check Mode",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "chargingTime": {
        "name": "Charging Time",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "chargingType": {
        "name": "Charging Type",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "inputMode": {
        "name": "Input Mode",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "BatVolt": {
        "name": "Battery Voltage",
        "type": "int",
        "unit": "V",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "voltage",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "clusterSw": {
        "name": "Cluster Switch",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "autoModel": {
        "name": "Auto Model",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "localState": {
        "name": "Local State",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "ctOff": {
        "name": "CT Off",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "OldMode": {
        "name": "Old Mode",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "pass": {
        "name": "Pass",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "getAll": {
        "name": "Get All",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "blueOta": {
        "name": "Bluetooth OTA",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
}


# Battery pack properties (9 per pack)
PACK_PROPERTIES: dict[str, PropertyDefinition] = {
    "batcur": {
        "name": "Battery Current",
        "type": "int",
        "unit": "A",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "current",
        "state_class": "measurement",
        "conversion": "value/10",
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "maxTemp": {
        "name": "Max Temperature",
        "type": "int",
        "unit": "°C",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "temperature",
        "state_class": "measurement",
        "conversion": "(value/10) - 273.15",
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "maxVol": {
        "name": "Max Voltage",
        "type": "int",
        "unit": "V",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "voltage",
        "state_class": "measurement",
        "conversion": "value/100",
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "minVol": {
        "name": "Min Voltage",
        "type": "int",
        "unit": "V",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "voltage",
        "state_class": "measurement",
        "conversion": "value/100",
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "power": {
        "name": "Pack Power",
        "type": "int",
        "unit": "W",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "power",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "socLevel": {
        "name": "SOC Level",
        "type": "int",
        "unit": "%",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "battery",
        "state_class": "measurement",
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "softVersion": {
        "name": "Software Version",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "state": {
        "name": "Pack State",
        "type": "int",
        "unit": None,
        "writable": False,
        "ha_entity": "sensor",
        "device_class": None,
        "state_class": None,
        "conversion": None,
        "min_value": None,
        "max_value": None,
        "step": None,
    },
    "totalVol": {
        "name": "Total Voltage",
        "type": "int",
        "unit": "V",
        "writable": False,
        "ha_entity": "sensor",
        "device_class": "voltage",
        "state_class": "measurement",
        "conversion": "value/100",
        "min_value": None,
        "max_value": None,
        "step": None,
    },
}


def apply_conversion(value: int | float, conversion: str | None) -> float:
    """Apply conversion formula to a value."""
    if conversion is None or value is None:
        return value
    
    try:
        # Safely evaluate the conversion formula
        return eval(conversion, {"__builtins__": {}}, {"value": value})
    except Exception:
        return value
